n_jobs: 2

plt_color: 'white'

quandl_key: '2MxCLy_zrKRvSsxCWs_v'
av_key: '3AWPS6G8YY4BIRPH'

n_stock_return: 10

ratio_thsld: 2
clip_thsld: 0.2

stock_volatility_min: 0.01
stock_volatility_max: 3

horizons: {'1d':1, '3d':3, '1w':5, '2w':10, '1m':21, '3m':63, '6m':126, '9m':189, '12m':252}
beta_window: 252

filing_start_date: '2008-01-01'
filing_end_date: '2018-03-31'

edgar_index_start_year: 2006
edgar_index_end_year: 2018
edgar_user_agent: 'alpharesearch10k10q@gmail.com' 

gpu_enabled: False
n_sample_per_cik: 1

retry_connect: 3
retry_backoff_factor: 0.5

