quandl_key: '2MxCLy_zrKRvSsxCWs_v'
av_key: '3AWPS6G8YY4BIRPH'

ratio_thsld: 2
clip_thsld: 0.2

stock_volatility_min: 0.01
stock_volatility_max: 3

horizons: {'1d':1, '3d':3, '1w':5, '2w':10, '1m':21, '3m':21*3, '6m':21*6, '9m':21*9, '12m':21*12}
beta_window: 252
